%% Midterm Exam, Question 2
% EECE5644
% Code generated by Benjamin Gincley
% 13 October 2019
%% Generate True [X,Y] and initialize figure
rng(5)
% Unit Circle
n = 1000; t = linspace(0,2*pi,n);
unit(1,:) = sin(t); unit(2,:) = cos(t);
figure()
xlabel('X Coordinate')
ylabel('Y Coordinate')
title('Contours of Object Localization Estimate using MAP, 4 Landmarks')
hold on
%line(unit(1,:),unit(2,:))
true_x = unit(1,:)*rand(1,1);
true_y = unit(2,:)*rand(1,1);
idx = round(n*rand(1,1));
trueX = [true_x(idx);true_y(idx)];
scatter(trueX(1),trueX(2),'gx')
%% Generate landmarks and calculate distance
landmark = zeros(2,4);
sigma = 0.3;
var = sigma^2*eye(2);
noise = 0.1^2*eye(2);
mu = [0;0];
for k = 1:4
    landmark(:,k) = [unit(1,k*(n/4)),unit(2,k*(n/4))];
    ni(k,:) = mvnrnd(mu,noise,1);
    trueR(k,:) = norm(trueX-landmark(:,k));
    r(k) = norm(trueX-landmark(:,k))+ni(k);
%     x_r = r(k)*unit(1,:)+landmark(1,k); 
%     y_r = r(k)*unit(2,:)+landmark(2,k);
%     l = line(x_r,y_r);
%     l.Color = 'k';
%     l.LineStyle = '--';
end
scatter(landmark(1,:),landmark(2,:),'ko')
%% Calculate posterior from Bayes and plot contours
logprior = -0.5*trueX'*inv(var)*trueX-log(2*pi*sigma*sigma);
step = 0.01;
x = -2:step:2;
y = x;
nTiles = size(x,2);
[meshX,meshY] = meshgrid(x,y);
Levels = -99:11:0;

% %1 Landmark:
% c = 1;
% posterior = findTargetQ2(c,x,landmark,r,var,logprior);
% contour(meshX,meshY,posterior,Levels)

% %2 Landmarks:
% c = 2;
% posterior = findTargetQ2(c,x,landmark,r,var,logprior);
% contour(meshX,meshY,posterior,Levels)

% %3 Landmarks: 
% c = 3;
% posterior = findTargetQ2(c,x,landmark,r,var,logprior);
% contour(meshX,meshY,posterior,Levels)

%4 Landmarks:
c = 4;
posterior = findTargetQ2(c,x,landmark,r,var,logprior);
contour(meshX,meshY,posterior,Levels)
%% Find the MAP predicted location
[MAPval, MAPcoord] = max(posterior(:));
MAP = [x(round(MAPcoord/nTiles));x(rem(MAPcoord, nTiles))]
scatter(MAP(1),MAP(2),'r+')

legend('True Location','Landmarks','Contour','Estimated Location')