%% Midterm Exam, Question 3
% EECE5644
% Code generated by Benjamin Gincley
% 13 October 2019
%% Generate Samples
mu = 0;
muVector = [0;0;0;0];
sigma = 1;
B = -10;
nGammas = 20;
I_s = sigma^2;
a = 1;
b = -0.1;
c = -0.25;
d = 0.025;
wTrue = [a,b,c,d]';
n_samples = 10;
gamma = zeros(1,20);
for i = 1:nGammas
    gamma(i) = 10^(B+i);
end
sqErrorMax = NaN(100,100);
sqErrorMin = NaN(100,100);
%%
for gammaIter = 1:nGammas
    for expIter = 1:100
        g = gammaIter;
        I_g = gamma(g)^2*eye(4);
        v = mvnrnd(mu,sigma,n_samples);
        prior = mvnrnd(muVector, I_g, 1);
        y = zeros(n_samples,1);
        x = y;
        for i = 1:n_samples
            x(i,1) = unifrnd(-1,1);
            y(i) = (a*x(i)^3)+(b*x(i)^2)+(c*x(i))+d;
        end
        D = [x,y];
%%
        wGuess = zeros(100,4);
        for i = 1:4
            wGuess(:,i) = mvnrnd(mu,sigma,100);
        end
        vGuess = mvnrnd(mu,sigma,100);
        eval_wGuess = (wGuess(:,1)*x(i)^3)+(wGuess(:,2)*x(i)^2)+(wGuess(:,3)*x(i))+wGuess(:,4)+vGuess;
        avgY = mean(y);
        loglikelihood = log(mvnpdf(eval_wGuess,avgY,sigma));
        logprior = log(mvnpdf(prior,muVector',I_g));
        obj = loglikelihood + logprior;
        [minObjVal, minObjIdx] = min(obj);
        [maxObjVal, maxObjIdx] = max(obj);
        min_wGuess = wGuess(minObjIdx,:)';
        max_wGuess = wGuess(maxObjIdx,:)';
        % obj = y/sigma^2 + x.^2/I_g

        sqErrorMax(gammaIter,expIter) = norm(wTrue - max_wGuess)^2;
        sqErrorMin(gammaIter,expIter) = norm(wTrue - min_wGuess)^2;

        if expIter == 100
            overallError0(gammaIter) = min(sqErrorMax(gammaIter,:));
            overallError25(gammaIter) = prctile(sqErrorMax(gammaIter,:),25);
            overallError50(gammaIter) = prctile(sqErrorMax(gammaIter,:),55);
            overallError75(gammaIter) = prctile(sqErrorMax(gammaIter,:),75);
            overallError100(gammaIter) = max(sqErrorMax(gammaIter,:));
        end
    end
end
%%
% figure()
% surface(1:100,1:100,sqErrorMin)
figure()
surface(1:100,1:100,sqErrorMax)
figure()
hold on
plot(-9:10,overallError0)
plot(-9:10,overallError25)
plot(-9:10,overallError50)
plot(-9:10,overallError75)
plot(-9:10,overallError100)
title('Squared Error for wMAP across log Gamma per 100 Experiments each')
ylabel('Squared Error')
xlabel('log10 Gamma')
legend('Min Error','25th Percentile','50th Percentile','75th Percentile','Max Error')