%% Midterm Exam, Question 3
% EECE5644
% Code generated by Benjamin Gincley
% 13 October 2019
%% Generate Samples
% l = 1000;
% est = linspace(1,100,l);
mu = 0;
muVector = [0;0;0;0];
sigma = 1;
B = -6;
for i = 1:11
    gamma(i) = 10^(B+i);
end
g = 4
I_g = gamma(g)^2*eye(4);
I_s = sigma^2;
a = 1;
b = -0.1;
c = -0.25;
d = 0.025;
wTrue = [a,b,c,d]';
n_samples = 10;
v = mvnrnd(mu,sigma,n_samples);
prior = mvnrnd(muVector, I_g, 1)
y = zeros(n_samples,1);
x = y;
for i = 1:n_samples
    x(i,1) = unifrnd(-1,1);
    y(i) = (a*x(i)^3)+(b*x(i)^2)+(c*x(i))+d;
end
D = [x,y];
%%
% likelihood = pdf('Normal',y,mu,sigma);
% loglikelihood = log(likelihood);
% logprior = log(pdf('Normal',prior,muVector,I_g));
% obj = loglikelihood + logprior;
% WMAP = inv(I_s + x'*x*I_g) * (y'*x*I_g);
% obj = y/sigma^2 + x.^2/I_g
WMAP = diag(I_g*sum(y) / (I_g*n_samples + I_s))

sqError = norm(wTrue - WMAP)^2
% W_test = repmat(est,[4 1]);
% %W_test = repmat(0.5,[4 1]);
% XT = zeros(4,1);
% XT(1) = sum(X3);
% XT(2) = sum(X2);
% XT(3) = sum(X1);
% XT(4) = sum(X0);
% WTrueX = (wTrue .* XT);
% Prior = WTrueX' * I_g * WTrueX;
% WTestX = zeros(l,l,4);
% for i=1:l
%     for j = 1:l
%         WTestX(i,j,:) = W_test(:,j) .* XT;
%         diff = permute(WTestX(i,j,:),[3 1 2])-WTrueX;
%         Likelihood(j) = diff' * I_s * diff;
%         Posterior(j) = Prior + Likelihood(j);
%     end
% end
% [MAPval, MAPidx] = min(Posterior,[],2);
% MAP = est(MAPidx)
% muPrior = [0,0,0,0]';
% wPrior = mvnrnd(muPrior,I_g,10);
% likelihood = mvnpdf(wPrior,muPrior',I_g);
% [MAP, idx] = max(likelihood .* wPrior, [],1);
% error = wTrue'-MAP;
% error = norm(error,2).^2;

% figure()
% plot(1:l,Posterior(1,:))

